package com.aiep.dundermifflin.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InformacionContactoEmpleadosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformacionContactoEmpleadosAllPropertiesEquals(
        InformacionContactoEmpleados expected,
        InformacionContactoEmpleados actual
    ) {
        assertInformacionContactoEmpleadosAutoGeneratedPropertiesEquals(expected, actual);
        assertInformacionContactoEmpleadosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformacionContactoEmpleadosAllUpdatablePropertiesEquals(
        InformacionContactoEmpleados expected,
        InformacionContactoEmpleados actual
    ) {
        assertInformacionContactoEmpleadosUpdatableFieldsEquals(expected, actual);
        assertInformacionContactoEmpleadosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformacionContactoEmpleadosAutoGeneratedPropertiesEquals(
        InformacionContactoEmpleados expected,
        InformacionContactoEmpleados actual
    ) {
        assertThat(expected)
            .as("Verify InformacionContactoEmpleados auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformacionContactoEmpleadosUpdatableFieldsEquals(
        InformacionContactoEmpleados expected,
        InformacionContactoEmpleados actual
    ) {
        assertThat(expected)
            .as("Verify InformacionContactoEmpleados relevant properties")
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()))
            .satisfies(e -> assertThat(e.getTipoFono()).as("check tipoFono").isEqualTo(actual.getTipoFono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformacionContactoEmpleadosUpdatableRelationshipsEquals(
        InformacionContactoEmpleados expected,
        InformacionContactoEmpleados actual
    ) {
        // empty method
    }
}
